version: '3'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - FLASK_APP=app.api  # Reference the api.py file where the app object is defined